include:
  - board: corneish_zen_mod_left@2.0.0//zmk
    snippet: zmk-usb-logging  # TEMPORARY: debug battery reading
    artifact-name: corneish_zen_mod_left_debug
  - board: corneish_zen_mod_left@2.0.0//zmk
  - board: corneish_zen_mod_right@2.0.0//zmk
  - board: corneish_zen_mod_left@2.0.0//zmk
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artifact-name: corneish_zen_v2_left_with_studio
