"""
Regenerate typeractive_bottom_profile.py from the source STL.

    python3 extract_profile.py [path/to/case-bottom-3dp-meshopt.stl]

Needs trimesh + shapely (system python3, not FreeCAD).

Method: slice the mesh horizontally, polygonize each section, and take the
outline at a level that avoids the top edge chamfer. Screw holes come from
the same section as inner rings. The skirt is NOT traced -- it is derived as
an inward offset of the outline, because the traced band is broken by the
wall cutouts and because wall thickness is what you actually want to edit.
"""

import sys, os, json, warnings
import numpy as np
import trimesh
from shapely.ops import polygonize, unary_union
from shapely.geometry import LineString

warnings.filterwarnings('ignore')

DEFAULT_STL = ('/Users/jackson/Downloads/3D-Prints/keyboards/'
               'typeractive-corne-choc/stl/case-bottom-3dp-meshopt.stl')
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                   'typeractive_bottom_profile.py')
PLAN = [0, 2]                 # mesh X, Z are the plan axes; Y is up

# Sample levels, mm in the STL frame.
LEVEL_OUTLINE = 2.60          # inside the plate, below the top chamfer
LEVEL_RIB = -9.00
LEVELS = {'plate_top': 3.532, 'plate_bottom': 2.034,
          'skirt_bottom': -6.90, 'rib_bottom': -12.965}
WALL_THICKNESS = 1.5
SIMPLIFY = 0.04

CUTOUTS = [
    dict(name='usb_port',  wall='+X', at=-2.087, along=1.960,
         width=16.00, y=-2.21, height=3.90),
    dict(name='side_port', wall='+Z', at=45.500, along=-13.990,
         width=10.95, y=-5.15, height=3.50),
]


def rings(mesh, y):
    sec = mesh.section(plane_origin=[0, y, 0], plane_normal=[0, 1, 0])
    if sec is None:
        return []
    segs = [LineString(sec.vertices[e.points][:, PLAN])
            for e in sec.entities if len(e.points) >= 2]
    ps = [p for p in polygonize(unary_union(segs)) if p.area > 0.05]
    ps = [p.simplify(SIMPLIFY, preserve_topology=True) for p in ps]
    return sorted(ps, key=lambda p: -p.area)


def coords(p):
    return [(round(x, 3), round(z, 3)) for x, z in p.exterior.coords[:-1]]


def main():
    stl = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_STL
    mesh = trimesh.load(stl)

    r = rings(mesh, LEVEL_OUTLINE)
    if not r:
        raise SystemExit('no section at Y=%s' % LEVEL_OUTLINE)
    outline, holes = r[0], r[1:]
    screws = sorted((round(h.centroid.x, 3), round(h.centroid.y, 3),
                     round(float(np.sqrt(h.area / np.pi)), 3)) for h in holes)
    rib = rings(mesh, LEVEL_RIB)[0]

    def fmt(pts):
        return '\n'.join('    (%9.3f, %9.3f),' % (x, z) for x, z in pts)

    body = TEMPLATE % {
        'stl': os.path.basename(stl),
        'outline': fmt(coords(outline)),
        'rib': fmt(coords(rib)),
        'plate_top': LEVELS['plate_top'],
        'plate_bottom': LEVELS['plate_bottom'],
        'skirt_bottom': LEVELS['skirt_bottom'],
        'rib_bottom': LEVELS['rib_bottom'],
        'wall': WALL_THICKNESS,
        'screws': '\n'.join('    (%9.3f, %9.3f, %6.3f),' % s for s in screws),
        'cutouts': '\n'.join(
            "    dict(name=%-12s wall=%-5s at=%9.3f, along=%9.3f,\n"
            "         width=%5.2f, y=%6.2f, height=%.2f)," %
            ("'%s'," % c['name'], "'%s'," % c['wall'], c['at'], c['along'],
             c['width'], c['y'], c['height']) for c in CUTOUTS),
    }
    open(OUT, 'w').write(body)
    print('outline %d pts, rib %d pts, %d screw holes -> %s'
          % (len(coords(outline)), len(coords(rib)), len(screws), OUT))


TEMPLATE = '''"""
Typeractive Corne Choc bottom case - extracted profile data.

GENERATED by extract_profile.py from %(stl)s.
Do not hand-edit the outlines; re-run the extractor instead. CUTOUTS is the
exception - it is meant to be edited (also mirrored in the extractor).

Coordinate frame is the STL's native frame, so these numbers line up with
the .step files and with shift_cutouts.py:

    X = case length      (mesh X)
    Z = case depth       (mesh Z)
    Y = height, up = +Y  (mesh Y)

The Fusion script maps mesh (X, Z, Y) -> Fusion (X, Y, Z); it only relabels
axes, so every number below is unchanged in the model.

How the shape was established:
  - the plate is 1.498 mm thick (Y 2.034 .. 3.532)
  - a 1.5 mm inward offset of the outline predicts a skirt band of
    601.8 mm2; the slice at Y=-2.0 measures 577.9 mm2, and the 23.9 mm2
    difference is exactly the USB port (16.0 wide x 1.5 wall). So the part
    is a uniform 1.5 mm shelled tray.
  - rebuilding from this data gives 19261 mm3 vs the mesh's 19187.7 mm3
    (+0.38%%, the residual being the top chamfer and corner radii), with a
    bounding box matching to within 0.02 mm on every axis.
"""

# Outer outline of the tray. Closed polygon, mm.
PLATE_OUTLINE = [
%(outline)s
]

# Small rib on the +X side, running below the skirt.
RIB_OUTLINE = [
%(rib)s
]

# Heights in mm, STL frame, +Y up.
LEVELS = {
    'plate_top':    %(plate_top).3f,
    'plate_bottom': %(plate_bottom).3f,
    'skirt_bottom': %(skirt_bottom).3f,
    'rib_bottom':   %(rib_bottom).3f,
}

# Uniform shell thickness; plate and wall agree to within 0.06 mm.
WALL_THICKNESS = %(wall)s

# Screw holes through the plate: (x, z, radius) mm.
SCREW_HOLES = [
%(screws)s
]

# Wall openings - this is the list you came here to edit.
#   wall:   which wall ('+X', '-X', '+Z', '-Z')
#   at:     position of that wall along its normal axis (mm)
#   along:  centre of the opening along the wall (mm)
#   width:  opening size along the wall (mm)
#   y:      centre height of the opening (mm)
#   height: opening height (mm)
CUTOUTS = [
%(cutouts)s
]
'''

if __name__ == '__main__':
    main()
