"""
Typeractive Corne Choc bottom case - extracted profile data.

GENERATED by extract_profile.py from case-bottom-3dp-meshopt.stl.
Do not hand-edit the outlines; re-run the extractor instead. CUTOUTS is the
exception - it is meant to be edited (also mirrored in the extractor).

Coordinate frame is the STL's native frame, so these numbers line up with
the .step files and with shift_cutouts.py:

    X = case length      (mesh X)
    Z = case depth       (mesh Z)
    Y = height, up = +Y  (mesh Y)

The Fusion script maps mesh (X, Z, Y) -> Fusion (X, Y, Z); it only relabels
axes, so every number below is unchanged in the model.

How the shape was established:
  - the plate is 1.498 mm thick (Y 2.034 .. 3.532)
  - a 1.5 mm inward offset of the outline predicts a skirt band of
    601.8 mm2; the slice at Y=-2.0 measures 577.9 mm2, and the 23.9 mm2
    difference is exactly the USB port (16.0 wide x 1.5 wall). So the part
    is a uniform 1.5 mm shelled tray.
  - rebuilding from this data gives 19261 mm3 vs the mesh's 19187.7 mm3
    (+0.38%, the residual being the top chamfer and corner radii), with a
    bounding box matching to within 0.02 mm on every axis.
"""

# Outer outline of the tray. Closed polygon, mm.
PLATE_OUTLINE = [
    (  -78.579,    50.306),
    (  -78.014,    50.684),
    (  -77.398,    50.911),
    (  -76.765,    50.984),
    (  -60.721,    50.967),
    (  -60.080,    50.894),
    (  -59.464,    50.676),
    (  -58.913,    50.311),
    (  -58.458,    49.833),
    (  -58.141,    49.289),
    (  -57.954,    48.720),
    (  -42.729,    48.712),
    (  -42.039,    48.623),
    (  -41.383,    48.372),
    (  -40.807,    47.959),
    (  -40.353,    47.424),
    (  -40.052,    46.816),
    (  -39.913,    46.214),
    (   -5.007,    46.230),
    (   -4.261,    46.124),
    (   -3.572,    45.848),
    (   -2.987,    45.394),
    (   -2.533,    44.810),
    (   -2.249,    44.120),
    (   -2.160,    43.422),
    (   -2.100,    -9.297),
    (   -2.160,   -10.376),
    (   -2.339,   -11.065),
    (   -2.640,   -11.741),
    (  -16.380,   -35.555),
    (  -16.892,   -36.156),
    (  -17.541,   -36.651),
    (  -18.279,   -36.991),
    (  -19.074,   -37.170),
    (  -19.885,   -37.178),
    (  -20.680,   -37.008),
    (  -21.419,   -36.683),
    (  -35.801,   -28.393),
    (  -68.369,   -23.989),
    (  -69.019,   -23.826),
    (  -69.636,   -23.509),
    (  -70.179,   -23.063),
    (  -78.429,   -11.707),
    ( -132.162,   -11.707),
    ( -132.869,   -11.625),
    ( -133.550,   -11.341),
    ( -134.142,   -10.887),
    ( -134.589,   -10.303),
    ( -134.873,    -9.621),
    ( -134.970,    -8.915),
    ( -134.962,    41.151),
    ( -134.881,    41.857),
    ( -134.597,    42.539),
    ( -134.142,    43.131),
    ( -133.558,    43.577),
    ( -132.877,    43.861),
    ( -132.162,    43.959),
    (  -97.574,    43.967),
    (  -97.574,    45.881),
    (  -97.476,    46.611),
    (  -97.200,    47.301),
    (  -96.746,    47.885),
    (  -96.162,    48.339),
    (  -95.472,    48.623),
    (  -94.750,    48.720),
    (  -79.509,    48.729),
    (  -79.337,    49.282),
    (  -79.022,    49.826),
]

# Small rib on the +X side, running below the skirt.
RIB_OUTLINE = [
    (   -4.604,   -12.151),
    (   -3.757,   -10.606),
    (   -3.596,    -9.976),
    (   -3.655,    43.644),
    (   -3.815,    44.056),
    (   -4.034,    44.339),
    (   -4.310,    44.550),
    (   -4.829,    44.731),
    (  -23.974,    44.729),
    (  -24.114,    44.881),
    (  -24.122,    46.077),
    (  -23.968,    46.230),
    (   -4.995,    46.236),
    (   -4.255,    46.136),
    (   -3.566,    45.854),
    (   -2.975,    45.400),
    (   -2.521,    44.810),
    (   -2.237,    44.120),
    (   -2.142,    43.392),
    (   -2.091,    -9.680),
    (   -2.148,   -10.382),
    (   -2.333,   -11.071),
    (   -2.688,   -11.837),
    (   -3.308,   -12.905),
    (   -3.510,   -12.954),
    (   -4.556,   -12.362),
]

# Heights in mm, STL frame, +Y up.
LEVELS = {
    'plate_top':    3.532,
    'plate_bottom': 2.034,
    'skirt_bottom': -6.900,
    'rib_bottom':   -12.965,
}

# Uniform shell thickness; plate and wall agree to within 0.06 mm.
WALL_THICKNESS = 1.5

# Screw holes through the plate: (x, z, radius) mm.
SCREW_HOLES = [
    ( -113.769,     7.730,  1.236),
    ( -113.769,    24.731,  1.236),
    (  -72.867,    -6.970,  1.237),
    (  -41.773,    28.133,  1.231),
    (  -28.365,   -13.571,  1.234),
]

# Wall openings - this is the list you came here to edit.
#   wall:   which wall ('+X', '-X', '+Z', '-Z')
#   at:     position of that wall along its normal axis (mm)
#   along:  centre of the opening along the wall (mm)
#   width:  opening size along the wall (mm)
#   y:      centre height of the opening (mm)
#   height: opening height (mm)
CUTOUTS = [
    dict(name='usb_port',  wall='+X', at=   -2.087, along=    1.960,
         width=16.00, y= -2.21, height=3.90),
    dict(name='side_port', wall='+Z', at=   45.500, along=  -13.990,
         width=10.95, y= -5.15, height=3.50),
]
